# Generated by Django 3.2.4 on 2022-03-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('userexam_id', models.IntegerField(unique=True, verbose_name='用户考试id')),
                ('exam_score', models.IntegerField(verbose_name='用户总得分')),
                ('total_score', models.IntegerField(verbose_name='试卷总分')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('exam_time', models.IntegerField(verbose_name='考试次数')),
                ('is_pass', models.BooleanField(default=False, verbose_name='是否通过')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '记录用户的每一次考试的每一道题的情况',
            },
        ),
        migrations.CreateModel(
            name='QuestionAudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('question', models.CharField(max_length=100, verbose_name='题目描述')),
                ('answer', models.CharField(max_length=50, verbose_name='答案')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('type', models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断'), ('文本资源评测', '文本资源评测'), ('医学标注资源评测', '医学资源评测'), ('文本听写', '文本听写')], max_length=40, verbose_name='题目类型')),
                ('audio_url', models.CharField(max_length=150, verbose_name='音频链接')),
            ],
            options={
                'verbose_name': '音频',
                'verbose_name_plural': '音频转写题型',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('test_id', models.IntegerField(verbose_name='试卷id')),
                ('question_id', models.IntegerField(verbose_name='题目id')),
                ('order', models.IntegerField()),
                ('is_abandon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库表，存储试卷所有的题目',
            },
        ),
        migrations.CreateModel(
            name='QuestionCheckbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('question', models.CharField(max_length=100, verbose_name='题目描述')),
                ('answer', models.CharField(max_length=50, verbose_name='答案')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('type', models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断'), ('文本资源评测', '文本资源评测'), ('医学标注资源评测', '医学资源评测'), ('文本听写', '文本听写')], max_length=40, verbose_name='题目类型')),
                ('a', models.CharField(max_length=20, verbose_name='A选项')),
                ('b', models.CharField(max_length=20, verbose_name='B选项')),
                ('c', models.CharField(max_length=20, verbose_name='C选项')),
                ('d', models.CharField(max_length=20, verbose_name='D选项')),
                ('e', models.CharField(max_length=20, verbose_name='E选项')),
            ],
            options={
                'verbose_name': '多选',
                'verbose_name_plural': '多选题型',
            },
        ),
        migrations.CreateModel(
            name='QuestionDiscuss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('question', models.CharField(max_length=100, verbose_name='题目描述')),
                ('answer', models.CharField(max_length=50, verbose_name='答案')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('type', models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断'), ('文本资源评测', '文本资源评测'), ('医学标注资源评测', '医学资源评测'), ('文本听写', '文本听写')], max_length=40, verbose_name='题目类型')),
                ('brief', models.CharField(max_length=150, verbose_name='简介')),
            ],
            options={
                'verbose_name': '论述',
                'verbose_name_plural': '论述题型',
            },
        ),
        migrations.CreateModel(
            name='QuestionJudge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('question', models.CharField(max_length=100, verbose_name='题目描述')),
                ('answer', models.CharField(max_length=50, verbose_name='答案')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('type', models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断'), ('文本资源评测', '文本资源评测'), ('医学标注资源评测', '医学资源评测'), ('文本听写', '文本听写')], max_length=40, verbose_name='题目类型')),
                ('choice', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=40, verbose_name='T|F')),
            ],
            options={
                'verbose_name': '判断',
                'verbose_name_plural': '判断题型',
            },
        ),
        migrations.CreateModel(
            name='QuestionMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('question', models.CharField(max_length=100, verbose_name='题目描述')),
                ('answer', models.CharField(max_length=50, verbose_name='答案')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('type', models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断'), ('文本资源评测', '文本资源评测'), ('医学标注资源评测', '医学资源评测'), ('文本听写', '文本听写')], max_length=40, verbose_name='题目类型')),
                ('a', models.CharField(max_length=20, verbose_name='A选项')),
                ('b', models.CharField(max_length=20, verbose_name='B选项')),
                ('c', models.CharField(max_length=20, verbose_name='C选项')),
            ],
            options={
                'verbose_name': '医学',
                'verbose_name_plural': '医学资源评测',
            },
        ),
        migrations.CreateModel(
            name='QuestionRadio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('question', models.CharField(max_length=100, verbose_name='题目描述')),
                ('answer', models.CharField(max_length=50, verbose_name='答案')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('type', models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断'), ('文本资源评测', '文本资源评测'), ('医学标注资源评测', '医学资源评测'), ('文本听写', '文本听写')], max_length=40, verbose_name='题目类型')),
                ('a', models.CharField(max_length=20, verbose_name='A选项')),
                ('b', models.CharField(max_length=20, verbose_name='B选项')),
                ('c', models.CharField(max_length=20, verbose_name='C选项')),
                ('d', models.CharField(max_length=20, verbose_name='D选项')),
            ],
            options={
                'verbose_name': '单选',
                'verbose_name_plural': '单选题型',
            },
        ),
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('question', models.CharField(max_length=100, verbose_name='题目描述')),
                ('answer', models.CharField(max_length=50, verbose_name='答案')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('type', models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断'), ('文本资源评测', '文本资源评测'), ('医学标注资源评测', '医学资源评测'), ('文本听写', '文本听写')], max_length=40, verbose_name='题目类型')),
                ('a', models.CharField(max_length=20, verbose_name='A选项')),
                ('b', models.CharField(max_length=20, verbose_name='B选项')),
                ('c', models.CharField(max_length=20, verbose_name='C选项')),
                ('d', models.CharField(max_length=20, verbose_name='D选项')),
                ('e', models.CharField(max_length=20, verbose_name='E选项')),
                ('f', models.CharField(max_length=20, verbose_name='F选项')),
                ('g', models.CharField(max_length=20, verbose_name='G选项')),
                ('h', models.CharField(max_length=20, verbose_name='H选项')),
            ],
            options={
                'verbose_name': '文本',
                'verbose_name_plural': '文本资源评测',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('test_id', models.IntegerField(verbose_name='试卷id')),
                ('question_id', models.IntegerField(verbose_name='题目id')),
                ('user_answer', models.TextField(verbose_name='用户答案')),
                ('user_score', models.IntegerField(verbose_name='用户得分')),
                ('exam_batch', models.IntegerField(verbose_name='考试批次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '记录用户的每一次考试的每一道题的情况',
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('description', models.CharField(max_length=30, verbose_name='简述')),
                ('introduction', models.CharField(max_length=200, verbose_name='简介')),
                ('re_exam', models.IntegerField(default=0)),
                ('extra_info', models.CharField(default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('pass_score', models.IntegerField(default=0, verbose_name='通过分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=15, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female')], verbose_name='年龄')),
                ('work_time', models.CharField(max_length=20, verbose_name='可工作时间')),
                ('lang', models.CharField(max_length=20, null=True, verbose_name='熟悉语种')),
                ('subject', models.CharField(max_length=20, null=True, verbose_name='熟悉领域')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '详细信息表',
            },
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('test_id', models.IntegerField(verbose_name='试卷id')),
            ],
            options={
                'verbose_name': '用户考试',
                'verbose_name_plural': '用户考试表，记录用户的考试信息',
                'unique_together': {('user_id', 'test_id')},
            },
        ),
    ]
